//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        private int ProviderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((this.ProviderIdField.Equals(value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ProviderName {
            get {
                return this.ProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderNameField, value) != true)) {
                    this.ProviderNameField = value;
                    this.RaisePropertyChanged("ProviderName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication14.ServiceReference3.HelloWorldResponse HelloWorld(WebApplication14.ServiceReference3.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication14.ServiceReference3.HelloWorldResponse> HelloWorldAsync(WebApplication14.ServiceReference3.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        WebApplication14.ServiceReference3.GetUsersResponse GetUsers(WebApplication14.ServiceReference3.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication14.ServiceReference3.GetUsersResponse> GetUsersAsync(WebApplication14.ServiceReference3.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersBYJSON", ReplyAction="*")]
        void GetUsersBYJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersBYJSON", ReplyAction="*")]
        System.Threading.Tasks.Task GetUsersBYJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBYID", ReplyAction="*")]
        void GetUserBYID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBYID", ReplyAction="*")]
        System.Threading.Tasks.Task GetUserBYIDAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetUserBYIDXMLResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBYIDXML", ReplyAction="*")]
        WebApplication14.ServiceReference3.GetUserBYIDXMLResponse GetUserBYIDXML(WebApplication14.ServiceReference3.GetUserBYIDXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBYIDXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication14.ServiceReference3.GetUserBYIDXMLResponse> GetUserBYIDXMLAsync(WebApplication14.ServiceReference3.GetUserBYIDXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication14.ServiceReference3.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication14.ServiceReference3.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication14.ServiceReference3.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication14.ServiceReference3.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication14.ServiceReference3.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(WebApplication14.ServiceReference3.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication14.ServiceReference3.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(WebApplication14.ServiceReference3.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication14.ServiceReference3.UserDto[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(WebApplication14.ServiceReference3.UserDto[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserBYIDXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserBYIDXML", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication14.ServiceReference3.GetUserBYIDXMLRequestBody Body;
        
        public GetUserBYIDXMLRequest() {
        }
        
        public GetUserBYIDXMLRequest(WebApplication14.ServiceReference3.GetUserBYIDXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserBYIDXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUserBYIDXMLRequestBody() {
        }
        
        public GetUserBYIDXMLRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserBYIDXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserBYIDXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication14.ServiceReference3.GetUserBYIDXMLResponseBody Body;
        
        public GetUserBYIDXMLResponse() {
        }
        
        public GetUserBYIDXMLResponse(WebApplication14.ServiceReference3.GetUserBYIDXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserBYIDXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication14.ServiceReference3.UserDto GetUserBYIDXMLResult;
        
        public GetUserBYIDXMLResponseBody() {
        }
        
        public GetUserBYIDXMLResponseBody(WebApplication14.ServiceReference3.UserDto GetUserBYIDXMLResult) {
            this.GetUserBYIDXMLResult = GetUserBYIDXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication14.ServiceReference3.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication14.ServiceReference3.WebService1Soap>, WebApplication14.ServiceReference3.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication14.ServiceReference3.HelloWorldResponse WebApplication14.ServiceReference3.WebService1Soap.HelloWorld(WebApplication14.ServiceReference3.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication14.ServiceReference3.HelloWorldRequest inValue = new WebApplication14.ServiceReference3.HelloWorldRequest();
            inValue.Body = new WebApplication14.ServiceReference3.HelloWorldRequestBody();
            WebApplication14.ServiceReference3.HelloWorldResponse retVal = ((WebApplication14.ServiceReference3.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication14.ServiceReference3.HelloWorldResponse> WebApplication14.ServiceReference3.WebService1Soap.HelloWorldAsync(WebApplication14.ServiceReference3.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication14.ServiceReference3.HelloWorldResponse> HelloWorldAsync() {
            WebApplication14.ServiceReference3.HelloWorldRequest inValue = new WebApplication14.ServiceReference3.HelloWorldRequest();
            inValue.Body = new WebApplication14.ServiceReference3.HelloWorldRequestBody();
            return ((WebApplication14.ServiceReference3.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication14.ServiceReference3.GetUsersResponse WebApplication14.ServiceReference3.WebService1Soap.GetUsers(WebApplication14.ServiceReference3.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public WebApplication14.ServiceReference3.UserDto[] GetUsers() {
            WebApplication14.ServiceReference3.GetUsersRequest inValue = new WebApplication14.ServiceReference3.GetUsersRequest();
            inValue.Body = new WebApplication14.ServiceReference3.GetUsersRequestBody();
            WebApplication14.ServiceReference3.GetUsersResponse retVal = ((WebApplication14.ServiceReference3.WebService1Soap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication14.ServiceReference3.GetUsersResponse> WebApplication14.ServiceReference3.WebService1Soap.GetUsersAsync(WebApplication14.ServiceReference3.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication14.ServiceReference3.GetUsersResponse> GetUsersAsync() {
            WebApplication14.ServiceReference3.GetUsersRequest inValue = new WebApplication14.ServiceReference3.GetUsersRequest();
            inValue.Body = new WebApplication14.ServiceReference3.GetUsersRequestBody();
            return ((WebApplication14.ServiceReference3.WebService1Soap)(this)).GetUsersAsync(inValue);
        }
        
        public void GetUsersBYJSON() {
            base.Channel.GetUsersBYJSON();
        }
        
        public System.Threading.Tasks.Task GetUsersBYJSONAsync() {
            return base.Channel.GetUsersBYJSONAsync();
        }
        
        public void GetUserBYID(int id) {
            base.Channel.GetUserBYID(id);
        }
        
        public System.Threading.Tasks.Task GetUserBYIDAsync(int id) {
            return base.Channel.GetUserBYIDAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication14.ServiceReference3.GetUserBYIDXMLResponse WebApplication14.ServiceReference3.WebService1Soap.GetUserBYIDXML(WebApplication14.ServiceReference3.GetUserBYIDXMLRequest request) {
            return base.Channel.GetUserBYIDXML(request);
        }
        
        public WebApplication14.ServiceReference3.UserDto GetUserBYIDXML(int id) {
            WebApplication14.ServiceReference3.GetUserBYIDXMLRequest inValue = new WebApplication14.ServiceReference3.GetUserBYIDXMLRequest();
            inValue.Body = new WebApplication14.ServiceReference3.GetUserBYIDXMLRequestBody();
            inValue.Body.id = id;
            WebApplication14.ServiceReference3.GetUserBYIDXMLResponse retVal = ((WebApplication14.ServiceReference3.WebService1Soap)(this)).GetUserBYIDXML(inValue);
            return retVal.Body.GetUserBYIDXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication14.ServiceReference3.GetUserBYIDXMLResponse> WebApplication14.ServiceReference3.WebService1Soap.GetUserBYIDXMLAsync(WebApplication14.ServiceReference3.GetUserBYIDXMLRequest request) {
            return base.Channel.GetUserBYIDXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication14.ServiceReference3.GetUserBYIDXMLResponse> GetUserBYIDXMLAsync(int id) {
            WebApplication14.ServiceReference3.GetUserBYIDXMLRequest inValue = new WebApplication14.ServiceReference3.GetUserBYIDXMLRequest();
            inValue.Body = new WebApplication14.ServiceReference3.GetUserBYIDXMLRequestBody();
            inValue.Body.id = id;
            return ((WebApplication14.ServiceReference3.WebService1Soap)(this)).GetUserBYIDXMLAsync(inValue);
        }
    }
}
